#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=1

start_service() {
    procd_open_instance
    procd_set_param command gunicorn
    procd_append_param command --chdir
    procd_append_param command /VM/server/
    procd_append_param command --bind
    procd_append_param command 192.168.3.1:8081
    procd_append_param command app:app
    procd_set_param stderr 1
    procd_set_param stdout 1
    procd_set_param pidfile /var/run/my_gunicorn_server.pid
    procd_close_instance
}

stop_service() {
    killall -9 gunicorn
}
